jobs:
- job: windows
  pool:
    vmImage: vs2017-win2016
  steps:
    - powershell: |
        Get-Service | Where-Object {$_.Status -eq "Running"}
      displayName: Show running services

#    - script: |
#        taskkill /f /im dotnet.exe
#        taskkill /f /im powershell.exe
    