steps:
# Ensure Node.js 10 is active
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Use Node.js 10'

- bash: |
    echo "$(printenv)"
    echo "JEST: ${JEST_DIR}"
    echo "TMP: ${TMP}"
    echo "TEMP: ${TEMP}"
    echo "os.tmpdir: $(node -p "const os=require('os');os.tmpdir();")"
    echo "path.resolve os.tmpdir a-test: $(node -p "const os=require('os');const path=require('path');path.resolve(os.tmpdir(), 'a-test');")"
    echo "process.env.TEMP: $(node -p "process.env.TEMP")"
    echo "process.env: $(node -p "JSON.stringify(process.env, null, 2);")"
    echo "cwd: $(node -p "const os=require('os');const path=require('path');const workingDir = process.cwd(); path.resolve(workingDir, '..');")"
    echo "hello"
  displayName: "Temp, current directory tests"

- bash: |
    npm ci
    node index.js
  displayName: "Use realpath-native"
