jobs:
- job: linux
  pool:
    vmImage: ubuntu-16.04
  steps:
    - template: azure-pipelines-steps.yml

#- job: macOS
  #pool:
   # vmImage: macos-10.13
  #steps:
    #- template: azure-pipelines-steps.yml
