pool: 
  vmImage: 'ubuntu-16.04'

steps:
- script: |
    npm adsf
    echo foo
  displayName: 'Script 1'
  condition: always()

- script: |
    set -e
    npm adsf
    echo foo
  displayName: 'Script 1'
  condition: always()

- script: |
    - npm adsf
    - echo foo
  displayName: 'Script 2'
  condition: always()

- script: |
    npm adsf && echo foo
  displayName: 'Script 3'
  condition: always()

- script: |
    npm adsf
    echo foo
  displayName: 'Script 4'
  condition: always()
