jobs:
# - job: windows
#   pool:
#     vmImage: vs2017-win2016
#   steps:
#     - template: azure-pipelines-steps.yml

# - job: linux
#   pool:
#     vmImage: ubuntu-16.04
#   steps:
#     - template: azure-pipelines-steps.yml

- job: macOS
  pool:
    vmImage: macos-10.13
  strategy:
    matrix:
      ruby_24:
        RUBY_VERSION: 2.4.6      
      ruby_21:
        RUBY_VERSION: 2.1.10
        BUNDLER_VERSION: 1.17.3
      ruby_head:
        RUBY_VERSION: ruby-head
  steps:
    - template: azure-pipelines-steps.yml

- job: Linux
  strategy:
    matrix:
      ruby_head:
        RUBY_IMAGE: ruby:latest
        RUBY_VERSION: ruby-head
        USE_RVM: true
  container: $[ variables.RUBY_IMAGE ]
  pool:
    vmImage: ubuntu-16.04