jobs:
- job: windows
  pool:
    vmImage: vs2017-win2016
  steps:
    - script: |
        reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" > t.txt
        type t.txt
        reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0" > t2.txt
        type t2.txt
      displayName: 'Show registry'
