#stages:
#- stage: build
jobs:
- job: publish
  pool:
    name: Default
  steps:
  - script: |
      md a1
      copy *.yml a1
    displayName: Copy files2

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: a1
      targetPath: '$(Build.SourcesDirectory)/a1'

- job: download
  dependsOn: publish
  pool:
    name: Default
  steps:
  - task: DownloadPipelineArtifact@1
    inputs:
      artifactName: a1
    displayName: 'Download a1 please'

# - stage: deploy
#   jobs:
#   - deployment: deploy
#     pool:
#       name: Default
#     environment: staging
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - download: current
#           - script: echo Hello
