jobs:
- job: windows
  pool:
    vmImage: vs2017-win2016
  steps:
    - script: |
        reg query /s "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" /s > t.txt
        echo Wow6432Node
        type t.txt
        
        echo VisualStudio\14.0
        reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0" /s > t2.txt
        type t2.txt
      displayName: 'Show registry'
