jobs:
# - job: windows
#   pool:
#     vmImage: vs2017-win2016
#   steps:
#     - template: azure-pipelines-steps.yml

# - job: linux
#   pool:
#     vmImage: ubuntu-16.04
#   steps:
#     - template: azure-pipelines-steps.yml

- job: macOS
  pool:
    vmImage: macos-10.13
  steps:
  - bash: echo "$(ruby --version)"
  - script: |
      echo "127.0.0.1 $(sudo scutil --get LocalHostName).local" | sudo tee -a /etc/hosts
    displayName: Fix hostname

  - script: printenv
    displayName: Dump environment variables

  - task: UseRubyVersion@0
    inputs:
      versionSpec: 2.6.2

  - script: script/setup-dependencies.sh
    displayName: Setup dependencies
