jobs:
- job: windows
  pool:
    vmImage: vs2017-win2016
  steps:
    - script: |
        #choco install hg
        #echo '##vso[task.setvariable variable=PATH]%PATH%'
      displayName: 'Install Mercurial'

    - script: |
        where hg
        hg --version
      displayName: 'Try gh'
