steps:
- task: NodeTool@0
  inputs:
    versionSpec: 8.10
  displayName: 'Install Node.js'    

- bash: npm --version
- bash: printenv    
- bash: |
    which npm
    npm i -g npm
    npm --version
    which npm
- bash: |
    which npm
    npm --version
