jobs:
- job: yarncache
  pool:
    name: Caching
  variables:  
    YARN_CACHE_FOLDER: $(Pipeline.Workspace)/yarn-cache
  steps:
  - task: RestoreCache@0
    inputs:
      key: '$(Build.SourcesDirectory)/yarn.lock'
      path: '$(YARN_CACHE_FOLDER)'

  - script: yarn --frozen-lockfile
    displayName: 'Run yarn'

  - task: SaveCache@0
    inputs:
      key: '$(Build.SourcesDirectory)/yarn.lock'
      path: '$(YARN_CACHE_FOLDER)'
