jobs:
- job: windows
  pool:
    vmImage: vs2017-win2016
  steps:
    - script: |
        reg query /s "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" /s > t.txt
        echo ===Wow6432Node===
        type t.txt

        echo ===VisualStudio\14.0===
        reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio" /s > t2.txt
        type t2.txt

        echo ====SBuild\ToolsVersions\4.0===
        reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild" /s > t3.txt
        type t3.txt 

        echo ===MSBuild===
        dir "C:\Program Files (x86)\MSBuild" /a:d /s /b > t4.txt
        type t4.txt    
      displayName: 'Show registry'

    - bash: |
        printenv
      displayName: 'Show env vars'
