steps:
- task: NodeTool@0
  inputs:
    versionSpec: 10.x
  displayName: 'Install Node.js'

- bash: |
    set -x
    npm install -g create-react-app@2.1.8
    create-react-app test-rc --typescript
    cd test-rc
    git init
    git add . 
    git commit -m "Test"
    git status
    echo yes | npm run eject
    yarn build
    yarn test --watch=no

- bash: |
    set -x
    cd $(TEMP)
    create-react-app test-rc2 --typescript
    cd test-rc2
    git init
    git add . 
    git commit -m "Test"
    git status
    echo yes | npm run eject
    yarn build
    yarn test --watch=no
