jobs:
- job: windows
  pool:
    vmImage: vs2017-win2016
  steps:
    - template: steps.yml

    - task: NodeTool@0
      inputs:
        versionSpec: 8.x
    - template: steps.yml

    - task: NodeTool@0
      inputs:
        versionSpec: 8.12
    - template: steps.yml
    
    - task: NodeTool@0
      inputs:
        versionSpec: 8.14
    - template: steps.yml
  
    - task: NodeTool@0
      inputs:
        versionSpec: 10.x
    - template: steps.yml
