jobs:
- job: CI
  strategy:
    maxParallel: 2
    matrix:
      Linux:
        vmImage: ubuntu-16.04
      Windows:
        vmImage: vs2017-win2016

  steps:
    - bash: |
        echo Commit SHA: $(Build.SourceVersion)
        git diff-tree --no-commit-id --name-only -r $(Build.SourceVersion)
        printenv
      displayName: 'Show commit files'
