jobs:
- job: windows
  pool:
    vmImage: vs2017-win2016
  steps:
  - script: |
      echo C:
      fsutil volume diskfree c:
      echo D:
      fsutil volume diskfree d:
    displayName: Show free disk space (Windows only)
    condition: eq(variables.AGENT_OS, 'Windows_NT')
