variables:  
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/yarn-cache

stages:
- stage: init
  jobs:
  - job: initcache
    strategy:
      matrix:
        linux:
          VM_IMAGE: ubuntu-16.04
        windows:  
          VM_IMAGE: vs2017-win2016
        macOS:
          VM_IMAGE: macOS-10.13
    pool:
      vmImage: $(VM_IMAGE)
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: 10.x
      displayName: 'Install Node 10.x'

    - script: yarn config set registry https://registry.npmjs.org/

    - script: yarn --frozen-lockfile
      displayName: 'Run yarn'

    - task: PublishPipelineArtifact@0
      inputs:
        targetPath: '$(YARN_CACHE_FOLDER)'
        artifactName: 'yarn-$(Agent.OS)'
      displayName: Publish yarn cache artifact

- stage: test
  jobs:
  - job: testcache
    strategy:
      matrix:
        linux:
          VM_IMAGE: ubuntu-16.04
        windows:  
          VM_IMAGE: vs2017-win2016
        macOS:
          VM_IMAGE: macOS-10.13
    pool:
      vmImage: $(VM_IMAGE)
    steps:
    - task: DownloadPipelineArtifact@1
      inputs:
        artifactName: 'yarn-$(Agent.OS)'
        targetPath: '$(YARN_CACHE_FOLDER)'
    
    - task: NodeTool@0
      inputs:
        versionSpec: 10.x
      displayName: 'Install Node 10.x'

    - script: yarn --frozen-lockfile
      displayName: 'Run yarn'
