jobs:
- job:
  strategy:
    matrix:
      windows:
        vmImage: 'vs2017-win2016'
      linux:
        vmImage: 'ubuntu-16.04'
      macos:
        vmImage: 'macos-10.13'
  pool:
    vmImage: $(vmImage)
  steps:
  - script: echo Hello, world! $(vmImage)
