jobs:
- job: windows
  pool:
    vmImage: vs2017-win2016
  steps:
    - script: |
        tasklist /fo csv > process.txt
        echo ##vso[task.uploadfile]process.txt
      displayName: Upload currents processes to text file

    - script: type process.txt

