jobs:
- job: publish
  pool:
    name: Default
  steps:
  - script: |
      md a1
      cp *.yml a1
    displayName: Copy files

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: a1
      targetPath: '$(Build.SourcesDirectory)/a1'

- job: download
  dependsOn: publish
  pool:
    name: Default
  steps:
  - download: current
