jobs:
- job: windows
  pool:
    vmImage: vs2017-win2016
  steps:
    - script: |
        dir "c:\Program Files"
        where hg
    - template: azure-pipelines-steps.yml

- job: linux
  pool:
    vmImage: ubuntu-16.04
  steps:
    - template: azure-pipelines-steps.yml

- job: macOS
  pool:
    vmImage: macos-10.13
  steps:
    - template: azure-pipelines-steps.yml
