steps:
- bash: |
    pushd $(Agent.ToolsDirectory)
    echo "$(find ./Ruby -type d)"
  continueOnError: true
  displayName: Show Ruby folders in Agent.ToolsDirectory

- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.4'
  displayName: Install Ruby

- bash: ruby --version
