jobs:
- job: yarncache
  pool:
    name: Default
  variables:  
    YARN_CACHE_FOLDER: $(Pipeline.Workspace)/yarn-cache
  steps:
  - restoreCache: package.json
    path: $(YARN_CACHE_FOLDER)

  - script: yarn --frozen-lockfile
    displayName: 'Run yarn'

  - saveCache: package.json
    path: $(YARN_CACHE_FOLDER)
