jobs:
- job: windows_2019
  pool: 'Hosted Windows 2019 with VS2019'
  steps:
    - script: |
        REG QUERY HKLM\Software\Microsoft\MSBuild /s > t.txt
        type t.txt        
    - template: azure-pipelines-steps.yml

- job: windows
  pool:
    vmImage: vs2017-win2016
  steps:
    - bash: which msbuild
    - template: azure-pipelines-steps.yml

- job: linux
  pool:
    vmImage: ubuntu-16.04
  steps:
    - template: azure-pipelines-steps.yml

- job: macOS
  pool:
    vmImage: macos-10.13
  steps:
    - template: azure-pipelines-steps.yml
