jobs:
- job: windows
  pool:
    vmImage: vs2017-win2016
  steps:
    - script: |
        tasklist /fo csv > %CD%\process.txt
        echo ##vso[task.uploadfile]%CD%\process.txt
      displayName: Upload currents processes to text file

    - script: type %CD%\process.txt
      condition: always()

