steps:
- task: NodeTool@0
  inputs:
    versionSpec: 10.x
  displayName: 'Install Node.js'

- bash: |
    git config --global user.name "Create React App"
    git config --global user.email "cra@email.com"  

- bash: |
    set -x
    npm install -g create-react-app@2.1.8
    create-react-app test-rc --typescript
    cd test-rc
    git init
    git add . 
    git commit -m "Test"
    git status
    echo yes | npm run eject
    echo "$(cat package.json)"
    rm -rf node_modules
    rm -rf yarn.lock
    yarn install --force
    yarn build
    yarn test --watch=no

- bash: |
    set -x
    cd $(TEMP)
    create-react-app test-rc2 --typescript
    cd test-rc2
    git init
    git add . 
    git commit -m "Test"
    git status
    echo yes | yarn run eject
    yarn build
    yarn test --watch=no
