steps:
- script: |
    npm adsf
    echo foo
  displayName: 'Script 1'

- script: |
    - npm adsf
    - echo foo
  displayName: 'Script 2'

- script: |
    npm adsf && echo foo
  displayName: 'Script 3'

- script: |
    npm adsf
    echo foo
  displayName: 'Script 4'

- script: |
  displayName: 'Script 1'
