jobs:
- job: windows
  pool:
    vmImage: vs2017-win2016
  steps:
    - script: |
        tasklist /fo csv > %CD%\process.csv
        echo ##vso[task.uploadfile]%CD%\process.csv
      displayName: Upload currents processes to text file

    - script: type %CD%\process.csv
      condition: always()

    - script: systeminfo
      condition: always()
      displayName: systeminfo

    - powershell: |
        Get-WmiObject Win32_Process | Select-Object CommandLine > d:\processes.txt
        type d:\processes.txt
        Write-Host "##vso[task.uploadfile]d:\processes.txt
