parameters:
  name: ''
  vmImage: ''
  steps: []
  matrix: {}

jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      ${{ each matrix in parameters.matrix }}:
        ${{ each pair in matrix }}:
          ${{ pair.key }}: ${{ pair.value }}
          IMAGE: ${{ matrix.key }}
  steps:
  - script: |
      echo "Common"
    displayName: 'Common pre-step'

  - ${{ parameters.steps }}
